name: Build Source

on:
    push:
        branches: [master]
    pull_request:

jobs:
    build-linux:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v6

            - uses: lukka/get-cmake@v4.3.2

            - name: Setup vcpkg
              uses: lukka/run-vcpkg@v11
              with:
                  vcpkgGitCommitId: "56bb2411609227288b70117ead2c47585ba07713"
                  vcpkgDirectory: "${{ github.workspace }}/vcpkg"

            - name: Configure CMake
              run: cmake -B build -DCMAKE_TOOLCHAIN_FILE=${{ github.workspace }}/vcpkg/scripts/buildsystems/vcpkg.cmake -DCMAKE_BUILD_TYPE=Release

            - name: Build
              run: cmake --build build --config Release -j$(nproc)

            - uses: actions/upload-artifact@v7
              with:
                  name: cubicdiscord-linux
                  path: build/CubicDiscord
